# -*- coding: utf-8 -*-
"""Google Trends API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Google_Trends_API.ipynb
"""

import pandas as pd
from pytrends.request import TrendReq
pytrend = TrendReq()

"""

---

"""

pytrends = TrendReq(hl='en-US', tz=360)
pytrends.build_payload(kw_list=['FEMA', 'Toolkit'], cat=0, geo="US")
# Interest by Region
df = pytrends.interest_over_time()

from matplotlib import pyplot as plt
df['FEMA'].plot(kind='line', figsize=(8, 4), title='FEMA')
plt.gca().spines[['top', 'right']].set_visible(False)

pytrends_MS = TrendReq(hl='en-US', tz=360)
pytrends_MS.build_payload(kw_list=['FEMA', 'Toolkit'], cat=0, geo="US-MS")

# Interest by Region
df_MS = pytrends_MS.interest_over_time()

df_MS['FEMA'].plot(kind='line', figsize=(8, 4), title='Searches for FEMA')

plt.gca().spines[['top', 'right']].set_visible(False)

pytrends_MS = TrendReq(hl='en-US', tz=360)
pytrends_MS.build_payload(kw_list=['FEMA', 'Toolkit'], cat=0, geo="US-MS")

# Interest by Region
df_MS = pytrends_MS.interest_over_time()

df_MS['FEMA'].plot(kind='line', figsize=(8, 4), title='Searches for FEMA')

plt.gca().spines[['top', 'right']].set_visible(False)

df_locs = pytrends_MS.interest_by_region()